name: Test and deploy from development

on:
  push:
    branches: [ development ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Test
      run: |
        npm install
        npm lint
        npm run test:ci
