name: Test and deploy from development

on:
  push:
    branches: [ development ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Test
      run: |
        npm install
        npm run lint
        npm run test:ci

  merge_to_master:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - uses: actions/checkout@master

      - name: Merge development to master
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: development
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
